// Code generated by MockGen. DO NOT EDIT.
// Source: repository/repository.go

// Package repositorymocks is a generated GoMock package.
package repositorymocks

import (
	context "context"
	model "redis/model"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetHuman mocks base method.
func (m *MockRepository) GetHuman(ctx context.Context, id string) (*model.Human, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHuman", ctx, id)
	ret0, _ := ret[0].(*model.Human)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHuman indicates an expected call of GetHuman.
func (mr *MockRepositoryMockRecorder) GetHuman(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHuman", reflect.TypeOf((*MockRepository)(nil).GetHuman), ctx, id)
}

// GetHumans mocks base method.
func (m *MockRepository) GetHumans(ctx context.Context) (*model.Humans, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHumans", ctx)
	ret0, _ := ret[0].(*model.Humans)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHumans indicates an expected call of GetHumans.
func (mr *MockRepositoryMockRecorder) GetHumans(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHumans", reflect.TypeOf((*MockRepository)(nil).GetHumans), ctx)
}
