name: Pipeline
on:
  push:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: 1.17
      - uses: golangci/golangci-lint-action@v2
        with:
          version: v1.45.2

      - name: lint
        run: make lint

      - name: build
        run: make build

      - name: test-unit
        run: make test-unit

      - name: test-coverage
        run: make test-coverage

      - name: upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
#          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true